apiVersion: v1
kind: Namespace
metadata:
  name: rabbitmq

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: rabbitmq
spec:
  ports:
  - name: http
    port: 15672
    targetPort: 15672
    nodePort: 32001
  - name: amqp
    port: 5672
    targetPort: 5672
    nodePort: 32002
  selector:
    app: rabbitmq
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
  namespace: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        ports:
        - name: http
          containerPort: 15672
        - name: amqp
          containerPort: 5672
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: "admin"
        - name: RABBITMQ_DEFAULT_PASS
          value: "fi@ph@ck@th0n"