name: .NET Build and Test + BD

on: 
  push:
    branches: [ "develop" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: "fi@ph@ck@th0n"
        ports:
          - 1433:1433
        options: >-
          --health-cmd "exit 0" 
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
      # Step 1: Check out the code from the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: Set up .NET environment
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: dotnet restore

      # Step 4:
      #- name: Update appsettings.json
      #  run: |
      #   sed -i 's|\"DefaultConnectionTesteIntegracao\": \"[^\"]*\"|\"DefaultConnectionTesteIntegracao\": \"Server=localhost,1433;Database=CadastroNumerosDB;User Id=sa;Password=FiapC#1234;TrustServerCertificate=True;Connection Timeout=30;\"|' ./CadastroNumeros.Api/appsettings.json
        
       
      # Build HealthMed.API
      - name: Build HealthMed.API
        run: dotnet build HealthMed/HealthMed.API/HealthMed.API.csproj --configuration Release --no-restore
      
      # Build HealthMed.AgendaConsumer
      - name: Build HealthMed.AgendaConsumer
        run: dotnet build HealthMed/HealthMed.AgendaConsumer/HealthMed.AgendaConsumer.csproj --configuration Release --no-restore
      
      # Build HealthMed.ConsultaAgendadaConsumer
      - name: Build HealthMed.ConsultaAgendadaConsumer
        run: dotnet build HealthMed/HealthMed.ConsultaAgendadaConsumer/HealthMed.ConsultaAgendadaConsumer.csproj --configuration Release --no-restore
      
      # Run tests
      - name: Run tests
        run: dotnet test HealthMed/HealthMed.Tests/HealthMed.Tests.csproj --configuration Release --verbosity normal

      